// clang-format Language: C
#ifndef MACROS_H
#define MACROS_H

#define MQ1_SINGLE_HEADER_BYTES 384

#define MQ1_SINGLE_HEADER_NUM_FIELDS 54

#define MQ1_QUAD_HEADER_BYTES 768

#define MQ1_QUAD_HEADER_NUM_FIELDS 138

#define MQ1_CHAR_LEN_HEADER_ID 4

#define MQ1_CHAR_LEN_PIXEL_DEPTH 4

#define MQ1_CHAR_LEN_SENSOR_LAYOUT 7

#define MQ1_CHAR_LEN_CHIP_SELECT 3

#define MQ1_CHAR_LEN_TIMESTAMP 27

#define MQ1_FLOAT_LEN_THRESHOLD 8

#define MQ1_CHAR_LEN_HEADER_EXTENSION_ID 5

#define MQ1_CHAR_LEN_EXTENDED_TIMESTAMP 31

#define MQ1_FIELDS_NUM_FIELDS 19

#define DAC_NUM_FIELDS 28

#define NUM_CHUNKSS_IN_CACHE 32

#endif
